removing pycache files and implementing more helpful error messages
This commit brings more helpful error messages for the case where a user
does have a global configuration, but a taxonomy directory has not been
set yet. In that case, rather than it being treated like `--no-config`
has been set, the user will now receive an error message that is
actually appropriate:

> ERROR: No taxonomy directory has been configured. Please run
'sylph-tax download --download-to <directory>' first, or specify
--taxonomy-dir.